Map<String, List<Map<String, Object?>>> beta06Snapshot({
  String bookId = 'book-beta06',
  String bookName = 'Beta Household',
}) {
  const created = 1767225600000;
  const transactionDate = 1785283200000;
  return {
    'household': [
      {
        'id': bookId,
        'name': bookName,
        'base_currency_code': 'IDR',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
        'remote_linked_at': created,
      },
    ],
    'members': [
      {
        'id': 'member-owner',
        'book_id': bookId,
        'display_name': 'Owner',
        'role': 'owner',
        'auth_user_id': 'remote-user-secret',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
      },
    ],
    'accounts': [
      {
        'id': 'account-cash',
        'book_id': bookId,
        'owner_member_id': 'member-owner',
        'name': 'Cash',
        'account_type': 'cash',
        'currency_code': 'IDR',
        'opening_balance': 1000000,
        'opening_balance_date': created,
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
      },
    ],
    'categories': [
      {
        'id': 'category-income',
        'book_id': bookId,
        'name': 'Salary',
        'category_type': 'income',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
      },
      {
        'id': 'category-expense',
        'book_id': bookId,
        'name': 'Groceries',
        'category_type': 'expense',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
      },
    ],
    'projects': [
      {
        'id': 'project-home',
        'book_id': bookId,
        'name': 'Home',
        'status': 'active',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
      },
    ],
    'transactions': [
      {
        'id': 'transaction-income',
        'book_id': bookId,
        'entered_by_member_id': 'member-owner',
        'project_id': 'project-home',
        'title': 'Salary',
        'category': 'Salary',
        'account': 'Cash',
        'transaction_date': transactionDate,
        'amount': 2500000,
        'transaction_type': 'income',
        'fee_amount': 0,
        'fee_treatment': 'none',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
      },
      {
        'id': 'transaction-expense',
        'book_id': bookId,
        'entered_by_member_id': 'member-owner',
        'project_id': 'project-home',
        'title': '=SUM(A1:A2)',
        'category': 'Groceries',
        'account': 'Cash',
        'transaction_date': transactionDate + 1000,
        'amount': 500000,
        'transaction_type': 'expense',
        'fee_amount': 0,
        'fee_treatment': 'none',
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
      },
    ],
    'asset_definitions': [
      {
        'id': 'asset-gold',
        'book_id': bookId,
        'display_name': 'Gold',
        'asset_kind': 'gold',
        'symbol': 'XAU',
        'provider_code': null,
        'provider_symbol': null,
        'exchange_code': null,
        'currency_code': 'IDR',
        'unit': 'gram',
        'lot_size': 1,
        'online_pricing_enabled': 0,
        'created_at': created,
        'updated_at': created,
        'deleted_at': null,
        'version': 1,
        'device_id': 'device-secret',
        'sync_status': 'synced',
      },
    ],
    'manual_market_prices': [
      {
        'book_id': bookId,
        'asset_key': 'asset-gold',
        'symbol': 'XAU',
        'price_minor': 1200000,
        'minor_unit_scale': 1,
        'currency_code': 'IDR',
        'unit': 'gram',
        'quoted_at': transactionDate,
        'source': 'manual',
        'is_delayed': 0,
        'is_manual': 1,
        'updated_at': transactionDate,
      },
    ],
  };
}
